apiVersion: v1
kind: Pod
metadata:
 name: azure-disk-pod
spec:
 containers:
  - image: microsoft/sample-aks-helloworld
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
 volumes:
      - name: azure
        azureDisk:
          kind: Managed
          diskName: myAKSDisk
          diskURI: /subscriptions/221065c7-99fe-4074-a24d-0e0ccc1fd5a8/resourceGroups/MC_benAKSGroup1_bkhub-cluster_centralus/providers/Microsoft.Compute/disks/myAKSDisk
