apiVersion: v1
kind: Pod
metadata:
  name: hello-world22234
spec:
  restartPolicy: Never
  containers:
    - name:  image
      image: "ubuntu:14.04"
      imagePullPolicy: Always
      ports: 
      - name: web
        containerPort: 80
        hostPort: 8080
      env:
      - name: MESSAGE
        value: "hi"
      command:  ["/bin/echo","hello","world"]
      args: ["/bin/echo \"${MESSAGE}\""]

