apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: Always
  containers:
    - name:  image
      image: "ubuntu:14.04"
      imagePullPolicy: Always
      env:
      - name: MESSAGE
        value: "hi"
      command:  ["/bin/echo","hello","world"]
      args: ["/bin/echo \"${MESSAGE}\""]

