apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: OnFailure
  containers:
    - name:  image
      image: "ubuntu:14.04"
      imagePullPolicy: Always
      command:  ["/bin/echo","hello","world"]

