apiVersion: v1
kind: PodTemplate
metadata:
  name: nginx
template:
    metadata:
      labels:
        app: nginx
    spec: 
      containers:
        - name:  nginx
          image: "nginx:alpine"
          imagePullPolicy: Always
          ports: 
          - containerPort: 80