apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp2
spec:
  replicas: 2
  selector:
    app: my-web
  template:
    metadata:
      labels:
        app: my-web
        
    spec: 
      containers:
        - name:  nginx
          image: "nginx:alpine"
          imagePullPolicy: Always
          ports: 
          - containerPort: 80
