apiVersion: v1
kind: Pod
metadata:
  name: hello-world2
spec:
  restartPolicy: Always
  containers:
    - name:  write
      image: "ubuntu:14.04"
      imagePullPolicy: Always
      command:  ["bash","-c","echo \"Hello world\" >> /data/hello"]
      volumeMounts:
        - name:  data
          mountPath:  /data
    - name:  hello
      image: "ubuntu:14.04"
      imagePullPolicy: Always
      command:  ["bash","-c","sleep 10; cat /data/hello"]
      volumeMounts:
        - name:  data
          mountPath:  /data
  volumes:
    - name:  data
      hostPath:
       path: /tmp
